version: '3.4'

services:
  doccomdb:
    container_name: DocComAPIDB
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=DocComAPIPW1!
  
        
  doccomapi:
    container_name: doc-com-api
    image: ${DOCKER_REGISTRY-}doccomapi
    build:
      context: .
      dockerfile: DocComAPI/Dockerfile
    ports:
        - 8001:80
    depends_on:
        - doccomdb
    environment:
      - DB_Host=doccomdb
      - DB_NAME=DocCom
      - DB_SA_PASSWORD=DocComAPIPW1!
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT:Development
  
  