name: Super-Linter

on: 
  push:
    paths-ignore:
      - 'packages/**'
      - 'DocComAPI/DocComAPI/bin/**'
      - 'DocComAPI/DocComAPI/obj/**'
      - 'DocComAPI/TestDocComAPI/bin/**'
      - 'DocComAPI/TestDocComAPI/obj/**'
      - 'DocComAPI/.vs/**'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRNACH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
